server:
    port: 8081

eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 2
    client:
        service-url:
            defaultZone:
                http://localhost:8761/eureka/
        healthcheck:
            enabled: true

spring:
    application:
        name: employee-service

    